const lucene = require("./src/index")(require("lucene"));
let result;

const data = [
  {
    gid: "1",
    cid: "ST01-001",
    n: "Monkey D. Luffy",
    t: "Straw Hat Crew/Captain",
    col: "1",
    cs: "0",
    a: "2",
    p: "5000",
    cp: null,
    l: "5",
    r: "1",
    ar: null,
    iu: "https://onepiece-cardgame.dev/images/cards/ST01-001_4f4b22_jp.jpg",
    e: "[Activate(Main)][Once Per Turn] Attach 1 of your rested Don!! cards to one of your Characters or this leader.",
    al: null,
    intl: "0",
    srcN: "Straw Hat Crew [ST-01]",
    srcD: "2022-12-01",
  },
  {
    gid: "5",
    cid: "ST01-005",
    n: "Jimbei",
    t: "Fish Man/Straw Hat Crew",
    col: "1",
    cs: "3",
    a: "2",
    p: "5000",
    cp: null,
    l: null,
    r: "2",
    ar: null,
    iu: "https://onepiece-cardgame.dev/images/cards/ST1-005_4aeedd_jp.jpg",
    e: "[DON!! x1] [When Attacking] 1 of your other Leader or Character cards gets +1000 power for the turn.",
    al: null,
    intl: "0",
    srcN: "Straw Hat Crew [ST-01]",
    srcD: "2022-12-01",
  },
  {
    gid: "6",
    cid: "ST01-014",
    n: "Guard Point",
    t: "Animal/Straw Hat Crew",
    col: "1",
    cs: "1",
    a: "0",
    p: null,
    cp: null,
    l: null,
    r: "2",
    ar: null,
    iu: "https://onepiece-cardgame.dev/images/cards/ST01-014_abbcae_jp.jpg",
    e: "[Counter] 1 of your Leaders or Characters gets +3000 power for the turn.\r\n[Trigger] 1 of your Leaders or Characters gets +1000 power for the turn.",
    al: null,
    intl: "0",
    srcN: "Straw Hat Crew [ST-01]",
    srcD: "2022-12-01",
  },
  {
    gid: "7",
    cid: "ST04-001",
    n: "Kaido",
    t: "Four Emperors/Animal Kingdom Pirates",
    col: "4",
    cs: "0",
    a: "2",
    p: "5000",
    cp: null,
    l: "5",
    r: "1",
    ar: "",
    iu: "https://onepiece-cardgame.dev/images/cards/ST04-001_cc24cb_jp.jpg",
    e: "[Activate(Main): DON!! -7] [Once Per Turn] Trash the top card of your opponent's life.",
    al: "",
    intl: "0",
    srcN: "Animal Kingdom Pirates [ST-04]",
    srcD: null,
  },
  {
    gid: "8",
    cid: "ST01-012",
    n: "Monkey D. Luffy",
    t: "Super Rookie/Straw Hat Crew",
    col: "1",
    cs: "5",
    a: "2",
    p: "6000",
    cp: null,
    l: null,
    r: "5",
    ar: "",
    iu: "https://onepiece-cardgame.dev/images/cards/ST01-012_168877_jp.jpg",
    e: "<Rush>(This Character can attack the turn it enters play.)\r\n[DON!! x2][When Attacking] Your opponent's can't activate <Blocker> for this battle.",
    al: "",
    intl: "0",
    srcN: "Straw Hat Crew [ST-01]",
    srcD: "2022-12-01",
  },
  {
    gid: "9",
    cid: "ST01-Chopper",
    n: "Tony Tony Chopper",
    t: "Animal/Straw Hat Crew",
    col: "1",
    cs: "1",
    a: "2",
    p: "1000",
    cp: null,
    l: null,
    r: "0",
    ar: null,
    iu: "https://onepiece-cardgame.dev/images/cards/ST01-Chopper_51ff99_jp.jpg",
    e: "<Blocker>(When your opponent attacks, by resting this card, you can change the attack target to this card)",
    al: null,
    intl: "0",
    srcN: "Straw Hat Crew [ST-01]",
    srcD: "2022-12-01",
  },
];

console.log(data.filter(lucene("\\[ST", true)).map((c) => c.n + " " + c.cid));
